version: '3'
services:
  customer-application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=my-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=<PASSWORD>
    ports:
      - 8080:8080
    depends_on:
      - my-postgres

  my-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - 5444:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - CSRF_DISABLE=False
    ports:
      - 5050:80
    depends_on:
      - my-postgres