apiVersion: v1
kind: Service
metadata:
  name: postgres-headless-service
  namespace: kube-dev
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
