apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: kube-dev
spec:
  selector:
    app: customer-application
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8080
  type: LoadBalancer
